- hosts: sdc
  tasks:
    # - debug: var=ansible_facts
    - debug:
        msg: "Setting up the core server"
    - name: Setup Postgres
      import_tasks: setup-postgres.yml
    - name: Setup PostgREST
      import_tasks: setup-postgrest.yml
    - name: Install Sqitch
      import_tasks: install-sqitch.yml
    - name: Clone AwesomeWiki application
      import_tasks: clone-application.yml
    - name: Install AwesomeWiki FDWs
      import_tasks: install-application-fdw.yml
    - name: Provision Database
      import_tasks: provision-db.yml
    - name: Setup client application
      import_tasks: setup-client-app.yml
    - name: Setup nginx
      import_tasks: setup-nginx.yml