- name: Install Git
  become: yes
  apt:
    pkg:
      - git
- name: Clone the AwesomeWiki Repo
  become: yes
  git:
    repo: 'https://github.com/AwesomeWiki/AwesomeWiki.git'
    dest: /var/AwesomeWiki
    version: "{{ branch | default('master', true) }}"
    force: yes