- name: Install Redis
  become: yes
  apt:
    pkg:
    - redis-server
- name: Copy Redis configuration
  become: yes
  copy:
    src: setup-redis/redis.conf
    dest: /etc/redis/redis.conf
    mode: 0640
    group: redis
    owner: redis
- name: Restart Redis
  become: yes
  service:
    name: redis
    state: restarted